version: '3.8'

services:
  pethelp.api:
    image: ${DOCKER_REGISTRY-}pethelpapi
    build:
      context: .
      dockerfile: PetHelp.API/Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"  # Mapeando a porta 8080 do container para a porta 8080 do host
      - "8081:8081"

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: pethelp_user
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: pethelp_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

